Update danielLevitas.md
brainlife/brainlife.hugo pull request #7
Opened 2022-01-26 17:53 UTC by dlevitas

2022-01-26 18:06 UTC, francopestilli requested changes

2022-01-26 18:06 UTC, francopestilli commented on content/team/danielLevitas.md
> +description : "Dan is a Psychology Ph.D. candidate at Indiana University. He is interested in affective salience processing, working under the direction of Dr. Thomas James. Dan is also one of the pr
I would change the last sentence to: "Dan is the primary developer of ezBIDS."

2022-01-26 18:11 UTC, dlevitas commented on content/team/danielLevitas.md
> +description : "Dan is a Psychology Ph.D. candidate at Indiana University. He is interested in affective salience processing, working under the direction of Dr. Thomas James. Dan is also one of the pr
okay

2022-06-10 00:37 UTC, francopestilli approved these changes

2022-06-10 00:38 UTC, francopestilli commented
I think I edited your Bio and Info I am closing this. You are welcome to reopen if you need specific info from this pull. @dlevitas

2022-06-10 00:38 UTC, closed without merging

2022-06-10 02:43 UTC, soichih commented
Please edit the ohbm2022 branch - in content/team.md